spring:
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: Safe Document
  datasource:
    url: jdbc:postgresql://localhost:5432/DocumentsDB
    username: docker
    password: docker
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /static/**

